parameters:
    # Vous pouvez conserver ces paramètres si vous en avez besoin ailleurs
    sp_data.resource_owner.youtube.video.class: SP\Bundle\DataBundle\ResourceOwner\Youtube\Video
    sp_data.resource_owner.youtube.playlistitems.class: SP\Bundle\DataBundle\ResourceOwner\Youtube\PlaylistItems
    sp_data.resource_owner.youtube.channel.class: SP\Bundle\DataBundle\ResourceOwner\Youtube\Channel
    sp_data.resource_owner.youtube.analytic.class: SP\Bundle\DataBundle\ResourceOwner\Youtube\Analytic\Channel
    sp_data.resource_owner.youtube.post.analytic.class: SP\Bundle\DataBundle\ResourceOwner\Youtube\Analytic\Post
    sp_data.resource_owner.facebook.posts.class: SP\Bundle\DataBundle\ResourceOwner\Facebook\Posts
    sp_data.resource_owner.facebook.post.class: SP\Bundle\DataBundle\ResourceOwner\Facebook\Post
    sp_data.resource_owner.facebook.post.analytic.class: SP\Bundle\DataBundle\ResourceOwner\Facebook\Analytic\Post
    sp_data.resource_owner.facebook.analytic.class: SP\Bundle\DataBundle\ResourceOwner\Facebook\Analytic\Channel
    sp_data.resource_owner.twitter.posts.class: SP\Bundle\DataBundle\ResourceOwner\Twitter\Posts
    sp_data.resource_owner.twitter.post.class: SP\Bundle\DataBundle\ResourceOwner\Twitter\Post
    sp_data.resource_owner.twitter.analytic.class: SP\Bundle\DataBundle\ResourceOwner\Twitter\Analytic\Channel
    sp_data.resource_owner.twitter.post.analytic.class: SP\Bundle\DataBundle\ResourceOwner\Twitter\Analytic\Post
    sp_data.resource_owner.instagram.posts.class: SP\Bundle\DataBundle\ResourceOwner\Instagram\Posts
    sp_data.resource_owner.instagram.post.class: SP\Bundle\DataBundle\ResourceOwner\Instagram\Post
    sp_data.resource_owner.instagram.post.analytic.class: SP\Bundle\DataBundle\ResourceOwner\Instagram\Analytic\Post
    sp_data.resource_owner.instagram.analytic.class: SP\Bundle\DataBundle\ResourceOwner\Instagram\Analytic\Channel
    sp_data.resource_owner.google.analytic.class: SP\Bundle\DataBundle\ResourceOwner\Google\Analytic\Channel
    sp_data.resource_owner.google.analytic.geographic.class: SP\Bundle\DataBundle\ResourceOwner\Google\Analytic\Geographic
    sp_data.resource_owner.google.analytic.demographic.class: SP\Bundle\DataBundle\ResourceOwner\Google\Analytic\Demographic
    sp_data.resource_owner.google.analytic.gender.class: SP\Bundle\DataBundle\ResourceOwner\Google\Analytic\Gender
    sp_data.resource_owner.tiktok.post.class: SP\Bundle\DataBundle\ResourceOwner\Tiktok\Post
    sp_data.resource_owner.tiktok.posts.class: SP\Bundle\DataBundle\ResourceOwner\Tiktok\Posts
    sp_data.resource_owner.tiktok.post.analytic.class: SP\Bundle\DataBundle\ResourceOwner\Tiktok\Analytic\Post
    sp_data.resource_owner.tiktok.analytic.class: SP\Bundle\DataBundle\ResourceOwner\Tiktok\Analytic\Channel

services:
    sp_data.resource_owner_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments: [[]]
        tags: ["container.service_locator"]
        public: false

    sp_data.utils.api_utils:
        public: true
        class: SP\Bundle\DataBundle\Utils\DataUtils
        arguments:
            - "@security.http_utils"
            - "@sp_data.resource_owner_locator"

    sp_data.abstract_resource_owner.generic:
        public: true
        abstract: true
        arguments:
            - "@sp_data.http_client"
            - "@security.http_utils"
            - {}
            - ~

    sp_data.abstract_resource_owner.oauth1:
        abstract: true
        parent: "sp_data.abstract_resource_owner.generic"
        class: SP\Bundle\DataBundle\ResourceOwner\GenericOAuth1ResourceOwner

    sp_data.abstract_resource_owner.oauth2:
        abstract: true
        parent: "sp_data.abstract_resource_owner.generic"
        class: SP\Bundle\DataBundle\ResourceOwner\GenericOAuth2ResourceOwner
